---
- name: Configure Credlancer environment
  hosts: localhost
  become: no

  tasks:
    - name: Update and upgrade apt packages
      become: yes
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Install development tools
      become: yes
      apt:
        state: present
        name:
          - git
          - nodejs
          - npm
          - xorg
          - xauth

    - name: Install Go version 1.18
      become: yes
      apt:
        state: present
        name: golang-1.18
        default_release: focal-updates

    - name: Install Electron
      become: yes
      npm:
        name: electron
        global: yes

    - name: Install ReactJS
      become: yes
      npm:
        name: create-react-app
        global: yes

    - name: Add deadsnakes repository
      become: yes
      apt_repository:
        repo: 'ppa:deadsnakes/ppa'

    - name: Install Python 3.9 tools
      become: yes
      apt:
        state: present
        name:
          - python3.9
          - python3.9-dev
          - python3.9-venv

    - name: Install Cairo requirement
      become: yes
      apt:
        state: present
        name: libgmp3-dev

    - name: Install Protostar
      command: "{{ item }}"
      loop:
       - wget -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh
       - /bin/bash install.sh
       - rm install.sh
       - /bin/bash -c 'source ~/.bashrc'
