---
- name: Configure Credlancer environment
  hosts: localhost
  become: yes

  tasks:
    - name: Install development tools
      become: yes
      apt:
        state: present
        name:
          - git

    #- name: Download Go binary
    #  become: yes
    #  get_url:
    #    url: https://go.dev/dl/go1.18.linux-amd64.tar.gz
    #    dest: /usr/local/
    #    mode: '644'

    - name: Unarchive Go binary
      become: yes
      unarchive:
        url: https://go.dev/dl/go1.18.linux-amd64.tar.gz
        dest: /usr/local/

    #- name: Extract Go binary
    #  become: yes
    #  command: "{{ item }}"
    #  loop:
    #    - tar -C /usr/local -xzf /usr/local/go1.18.linux-amd64.tar.gz
    #    - rm /usr/local/go1.18.linux-amd64.tar.gz

    - name: Add Go binary to PATH
      lineinfile:
        dest: ~/.bashrc
        line: "{{ item }}"
      loop:
        - 'export GOROOT=/usr/local/go'
        - 'export GOPATH=$HOME/go'
        - 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH'

    - name: Setting Go Environment
      command: /bin/bash -c 'source ~/.bashrc'
